version: '3.3'
services:
    neo4j:
        container_name: testneo4j
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - '$HOME/neo4j/data:/data'
            - '$HOME/neo4j/conf:/var/lib/neo4j/conf'
            - '$HOME/neo4j/logs:/logs'
            - '$HOME/neo4j/import:/var/lib/neo4j/import'
            - '$HOME/neo4j/plugins:/plugins'
            - './KEP.csv:/KEP.csv'
        environment:
            - NEO4J_AUTH=none
        image: 'neo4j:latest'
